name: Docker Compose CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Start Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Print Docker Compose Logs
        run: |
          docker-compose logs
